[package]
name = "home-drive"
version = "0.1.0"
edition = "2021"

[dependencies]
tide = { version = "0.16.0" }
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.33.0", features = ["full"] }
femme = "2.2.1"
